import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} antialiased min-h-screen bg-[#e6eef7] relative`}>
        <div className="fixed inset-0 -z-10 bg-[url('/bg.jpg')] bg-center bg-cover bg-fixed" />
        <div className="fixed inset-0 -z-10 bg-black/10" />
        <div className="relative">
          {children}
        </div>
      </body>
    </html>
  );
}

